### ISSUE TITLE
fs.write calls missing non-optional (as of node v10.0.0) callback

### ISSUE THREAD

**Issue by thisdotrob** [GowerStreet/sibilant#1]
https://nodejs.org/api/fs.html#fs_fs_write_fd_string_position_encoding_callback

e.g.: https://github.com/GowerStreet/sibilant/blob/27c8a44613d24ed3a6b72b8057b20121569796fa/lib/repl.js#L110

These lines cause a TypeError as the callback is undefined.

**Comment by sleepyfox** [comment]
That's compiled code, the original is here:
https://github.com/GowerStreet/sibilant/blob/27c8a44613d24ed3a6b72b8057b20121569796fa/src/repl.sibilant#L78
and here:
https://github.com/GowerStreet/sibilant/blob/27c8a44613d24ed3a6b72b8057b20121569796fa/src/repl.sibilant#L91

**Comment by thisdotrob** [comment]
Fixed
